// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdqfImSCqjEF4XWEaQp-IiM0cTlZjIwrE',
    appId: '1:374459833448:web:67431453d3caa80644afdd',
    messagingSenderId: '374459833448',
    projectId: 'kds-tfg',
    authDomain: 'kds-tfg.firebaseapp.com',
    storageBucket: 'kds-tfg.firebasestorage.app',
    measurementId: 'G-4FGT7Y6LYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIOYrnMSHfwjnUwMzAIVhEsMJrJRWAFC8',
    appId: '1:374459833448:android:1213928dda4de31344afdd',
    messagingSenderId: '374459833448',
    projectId: 'kds-tfg',
    storageBucket: 'kds-tfg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsIn_3w7lbkbUmKpD-Al8Zxva0C-tjt3w',
    appId: '1:374459833448:ios:e90c4cfcb70ccd2444afdd',
    messagingSenderId: '374459833448',
    projectId: 'kds-tfg',
    storageBucket: 'kds-tfg.firebasestorage.app',
    iosBundleId: 'com.kdskull.kdsCocina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsIn_3w7lbkbUmKpD-Al8Zxva0C-tjt3w',
    appId: '1:374459833448:ios:e90c4cfcb70ccd2444afdd',
    messagingSenderId: '374459833448',
    projectId: 'kds-tfg',
    storageBucket: 'kds-tfg.firebasestorage.app',
    iosBundleId: 'com.kdskull.kdsCocina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdqfImSCqjEF4XWEaQp-IiM0cTlZjIwrE',
    appId: '1:374459833448:web:df6f14a0e543f73044afdd',
    messagingSenderId: '374459833448',
    projectId: 'kds-tfg',
    authDomain: 'kds-tfg.firebaseapp.com',
    storageBucket: 'kds-tfg.firebasestorage.app',
    measurementId: 'G-DZYK0W0JFE',
  );
}
